### ISSUE TITLE
CUDA 11

### ISSUE THREAD

**Issue by filaPro** [lilanxiao/Rotated_IoU#14]
Hi @lilanxiao ,
Looks like this code can't be compiled with cuda11. Can you please have a look at it?

**Comment by lilanxiao** [comment]
Hi @filaPro ,

I've only tested my code with Pytorch 1.5 and CUDA-Toolkit-10.2. But the problem is probably not the CUDA version, since I only use the most basic CUDA APIs. According to the [home page of Pytorch](https://pytorch.org/get-started/previous-versions/), it supports CUDA 11 since 1.6 version. I assume that you complied the code with a newer Pytorch version. 

I guess the Pytorch team has probably changed some APIs of its C++ backend in the 1.6 or 1.7, so that my code cannot be compiled anymore. I've seen a similar issue when I tried to compile some legacy code written at the time of Pytorch 1.0 with Pytorch 1.5. I saw tons of errors from the C++ backend of Pytorch. Simply updating the legacy code with newer APIs solved the issue. CUDA version didn't really matter. 

I'm sorry that I don't have enough time to add support for a newer Pytorch, since I'm struggling with my own deadlines. I suggest you check the C++ APIs of Pytorch. I hope it would help.
