### ISSUE TITLE
Why are we sorting vertices to calculate 2D intersection?

### ISSUE THREAD

**Issue by JonathanCMitchell** [lilanxiao/Rotated_IoU#15]
I don't understand why we have to introduce the sort function to calculate the 2D intersection between oriented bounding boxes. 
I have seen other implementations that can calculate it by looping through the two rectangles and finding the vertices that indicate a polygon intersection shape, then they just calculate the area of that shape using this formula:
![image](https://user-images.githubusercontent.com/13068956/112551588-7d267480-8d7e-11eb-99b5-e44bccce7c03.png)

https://github.com/maudzung/Complex-YOLOv4-Pytorch/blob/master/src/utils/cal_intersection_rotated_boxes.py#L42
https://developer.nvidia.com/blog/detecting-rotated-objects-using-the-odtk/

I'm just not sure why this sort() method is necessary.

**Comment by lilanxiao** [comment]
The formula is called "shoelace formula". This formula requires that all vertices must be sorted in clockwise or counter-clockwise order. 

For the intersection of boxes, there are two types of vertices. "intersections of edges" and "corners in boxes", as the green ones and red ones in [this Picture](https://developer-blogs.nvidia.com/wp-content/uploads/2020/06/polygon-for-overlapping-rotated-rectangles-1.png) show. The basic idea of my code is: 

1. find these two types of vertices, respectively
2. sort them in clockwise/counter-clockwise order
3. use the shoelace formula to get the area. 

My implementation needs this sort() because it finds the two types of vertices separately, which is intuitive and naive. The other implementations use a more elegant "sequential cutting" algorithm to find all vertices at once. To be honest, I'm not an expert in geometry. But this algorithm seems to provide sorted intersection points directly so that there is no need to sort them afterward. 

I think the "sequential cutting" is probably faster than my implementation but the result should be the same.

**Comment by JonathanCMitchell** [comment]
ok that makes sense. My only concern is how that sort will affect the backwards pass when differentiating.

**Comment by lilanxiao** [comment]
The back-propagation is explained in issue #7. The trick is to use torch.gather() and the sorting itself doesn't need a backward pass.
