### ISSUE TITLE
Is this method can used by arbitrary polygons?

### ISSUE THREAD

**Issue by liuchangf** [lilanxiao/Rotated_IoU#25]
Hello There:

Geat job!!

Is the idear for this method can be used by arbitrary polygons?

**Comment by lilanxiao** [comment]
hi, I think it's possible. The idea is actually simple: 
1. find all vertices of the intersection polygon
2. sort these vertices
3. apply shoelace formula to calculate the area
4. find the smallest enclosing box if necessary
My implementation uses the brute force method in Step 1 and 4. The brute force method works fine since I only consider rectangles. If you want to extend my code to arbitrary polygons (especially those with many vertices), you should probably consider replacing the brute force algorithms with more elegant ones to save memory usage and faster speed.

**Comment by sanagno** [comment]
Hi @liuchangf, if you have any updates on that, highly appreciated!

**Comment by HolyCrap96** [comment]
Can I use this implementaton to calculate the IoU of quadrangles without any modification?

**Comment by lilanxiao** [comment]
> Can I use this implementaton to calculate the IoU of quadrangles without any modification?

no, my code only works with rectangles. At least two functions assume that the inputs are rectangles.

- `box1_in_box2` in `box_intersection.py`: it uses the properties of rectangles to simplify the calculation. 
- `box2corners_th` in `oriented_iou_loss.py`: it calculates the corner coordinates of rectangles. 

Other functions should work with arbitrary quadrangles, as far as I can see. If you need support for arbitrary quadrangles, feel free to modify these two functions and see what happens.

**Comment by HolyCrap96** [comment]
thanks! I'll give it a try after I'm done with the work at hand.
