### ISSUE TITLE
Not able to run Rotated_IoU in Spyder but works in Anaconda Prompt

### ISSUE THREAD

**Issue by dominikj2** [lilanxiao/Rotated_IoU#26]
Hi,

I managed to run Rotated_IoU in the Anaconda Prompt by first running setup.py and then running demo.py.

I am not experienced with CUDAExtensions but when I try to run in spyder, i get the following error with setup.py:

```
DistutilsArgError: no commands supplied


During handling of the above exception, another exception occurred:

SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```
What are the required commands?

I am an R user that is trying to translate Rotated_IoU code into R. Can you explain why I can not get it to run in spyder?

**Comment by lilanxiao** [comment]
Hi, I'm not familiar with Spyder since I use VS Code. But I think the console in Spyder is not a terminal but an ipython console. In an ipython console, one cannot run a python script by simply typing its name. The Anaconda Prompt works since it's able call the python interpreter. 
Perhaps you can try this trick here: 
https://stackoverflow.com/questions/11744181/running-python-script-inside-ipython

**Comment by dominikj2** [comment]
Fantastic. That worked. Thank you
