### ISSUE TITLE
PyTorch1.2 and CUDA10.0  

### ISSUE THREAD

**Issue by ChunmianLin** [lilanxiao/Rotated_IoU#28]
Hi, thanks for your great job.
I encountered some bugs in environment configuration: when I ran 'python set_up.py install', the error occured as follows. Due to some configurations in my machine, the pytorch and cuda verision must be 1.2 and 10.0.

So, does the code support such low-version environment setting? Or, how to modify the code to match my system environment? 
I am not familiar with CUDA or C/C++ compilation, and I  really need your helps.

Thanks in advanced.

**Comment by ChunmianLin** [comment]
![Screenshot from 2021-08-12 17-03-17](https://user-images.githubusercontent.com/53289159/129169792-d1f11d16-9a61-4193-b0c1-d8ca1ab69d9f.png)

**Comment by lilanxiao** [comment]
hi, my code doesn't support Pytorch 1.2, because some C++ APIs of Pytorch have been changed somewhere between 1.4 and 1.5 if I remember it correctly. The CUDA 10.0 is probably OK, because I only use very basic CUDA features. 

I think it's possible to make it work with Pytorch 1.2. At least two places should be modified:

1. all `tensor.data_ptr<T>()` should be replaced with `tensor.data<T>()`.
2. all `TORCH_CHECK` macro in `utils.h` should be replaced with `AT_CHECK`.

Other modifications can be done by trial and error.

**Comment by ChunmianLin** [comment]
> hi, my code doesn't support Pytorch 1.2, because some C++ APIs of Pytorch have been changed somewhere between 1.4 and 1.5 if I remember it correctly. The CUDA 10.0 is probably OK, because I only use very basic CUDA features.
> 
> I think it's possible to make it work with Pytorch 1.2. At least two places should be modified:
> 
> 1. all `tensor.data_ptr<T>()` should be replaced with `tensor.data<T>()`.
> 2. all `TORCH_CHECK` macro in `utils.h` should be replaced with `AT_CHECK`.
> 
> Other modifications can be done by trial and error.

Many thanks.
1. CUDA10 encountered error information like: 'CUDA kernel failed, invalid device function';
<img width="910" alt="1628854153(1)" src="https://user-images.githubusercontent.com/53289159/129350782-e11d5241-1eba-48de-8e66-cb1e1df6611a.png">
2. Sorry, how to understand the two modifications you mentioned? What does the 'tensor.data_ptr<T>()' and 'TORCH_CHECK' mean?

**Comment by lilanxiao** [comment]
hi, I mean you should modify the C++ source code. 
First, change line 23-24 of [cuda_op/sort_vert.cpp](https://github.com/lilanxiao/Rotated_IoU/blob/master/cuda_op/sort_vert.cpp#L23) from
```
sort_vertices_wrapper(b, n, m, vertices.data_ptr<float>(), mask.data_ptr<bool>(),
                         num_valid.data_ptr<int>(), idx.data_ptr<int>());
```
to
```
sort_vertices_wrapper(b, n, m, vertices.data<float>(), mask.data<bool>(),
                         num_valid.data<int>(), idx.data<int>());
```
Since `tensor.data_ptr<T>` is a new API and not supported in old Pytorch versions.

Second, [cuda_op/utils.h](https://github.com/lilanxiao/Rotated_IoU/blob/master/cuda_op/utils.h) uses the macro `TORCH_CHECK`, which is probably not supported in old Pytorch versions. You should replace all `TORCH_CHECK` in the file to `AT_CHECK`.

I don't have CUDA-toolkit 10.0 on my machine so I cannot test these changes. I'm not sure if they would work. If you meet further issues, I recommend you to focus on the C++ APIs of Pytorch. Other parts should be OK.

**Comment by ChunmianLin** [comment]
Many thanks! It is successful  to compile on the PyTorch1.2 and CuDA10.0 by converting 'tensor.data_ptr<>' and 'TORCH_CHECK' that you mentioned, and another data type in 'box_intersection_2d.py' and 'min_enclosing_box.py'.

Thanks again for your help.

**Comment by ChunmianLin** [comment]
By the way, if I want to use it for KITTI loss calculation, how should I do?
